name: ml
dependencies:
  - jupyter=1.0.*
  - matplotlib=3.1.*
  - numpy=1.16.*
  - pandas=0.24.*
  - python=3.7.*
  - scikit-learn=0.21.*
  - scipy=1.3.*
  - seaborn=0.9.*
  - tensorflow=1.14.*
  - python-graphviz=0.10.*
